// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'apps/web/public/**',
      // Generated by Next on every build; not ours to lint.
      'apps/web/next-env.d.ts',
      // Generated by `expo prebuild` and filled in by a native build.
      'apps/mobile/android/**',
      'apps/mobile/ios/**',
      'apps/mobile/.expo/**',
      'prisma/migrations/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // `== null` is permitted, and only that: it is the idiomatic way to test
      // for null-or-undefined together, which matters where Prisma returns null
      // and an absent field is undefined. Every other loose comparison is an error.
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'no-restricted-globals': [
        'error',
        {
          name: 'setInterval',
          message:
            'Polling is not a substitute for the realtime architecture. Use the event bus / scheduler abstractions.',
        },
      ],
    },
  },
  {
    /**
     * NestJS resolves constructor dependencies from `emitDecoratorMetadata`,
     * which only records a class when it was imported as a *value*. A
     * type-only import erases to `Function` and the container cannot resolve
     * it, so this rule is off for the Nest applications by necessity, not by
     * preference. The domain packages below keep it on.
     */
    files: ['apps/api/**/*.ts', 'apps/worker/**/*.ts'],
    rules: {
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },
  {
    /**
     * `request.ip` is the socket address, which behind nginx is the proxy.
     * Every session, audit row and rate-limit bucket that read it recorded
     * the same container address until the request middleware started
     * resolving the real caller. The three files below are the resolution
     * itself and its fallbacks; everything else goes through `clientAddress`
     * or `request.client`.
     */
    files: ['apps/api/src/**/*.ts'],
    ignores: [
      'apps/api/src/common/request-context.ts',
      'apps/api/src/common/throttler-tracker.ts',
      'apps/api/src/security/ip-rules.guard.ts',
      'apps/api/src/security/ip-rules.controller.ts',
      'apps/api/src/**/*.test.ts',
    ],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "MemberExpression[property.name='ip'][object.name=/^(req|request)$/]",
          message:
            'request.ip is the proxy behind nginx. Use clientAddress(request) to record an address, or request.client to decide on one.',
        },
      ],
    },
  },
  {
    // Pure domain packages must never depend on frameworks or I/O.
    files: [
      'packages/financial-core/**/*.ts',
      'packages/trading-core/**/*.ts',
      'packages/risk-core/**/*.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: 'react', message: 'Domain packages must stay framework-independent.' },
            { name: 'next', message: 'Domain packages must stay framework-independent.' },
            { name: '@nestjs/common', message: 'Domain packages must stay framework-independent.' },
            { name: '@nestjs/core', message: 'Domain packages must stay framework-independent.' },
            {
              name: '@prisma/client',
              message: 'Domain packages must not depend on infrastructure.',
            },
            { name: 'ioredis', message: 'Domain packages must not depend on infrastructure.' },
          ],
          patterns: [
            {
              group: ['node:*', 'fs', 'http', 'https', 'net'],
              message: 'Domain packages must be pure and I/O free.',
            },
          ],
        },
      ],
    },
  },
  {
    /**
     * React Native resolves bundled assets through `require` with a literal
     * path — Metro rewrites those at build time, and an `import` of a `.wav`
     * resolves to nothing at runtime with no error. The rule is right
     * everywhere else, so it is turned off for the one file that has to break
     * it rather than for the app.
     */
    files: ['apps/mobile/src/lib/sound-player.ts'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    files: [
      '**/*.spec.ts',
      '**/*.test.ts',
      'scripts/**/*.ts',
      'prisma/seed.ts',
      // A command-line tool's output is its interface.
      'apps/api/src/cli/**/*.ts',
    ],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-restricted-imports': 'off',
    },
  },
);
