// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'apps/web/public/**',
      // Generated by Next on every build; not ours to lint.
      'apps/web/next-env.d.ts',
      'prisma/migrations/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // `== null` is permitted, and only that: it is the idiomatic way to test
      // for null-or-undefined together, which matters where Prisma returns null
      // and an absent field is undefined. Every other loose comparison is an error.
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'no-restricted-globals': [
        'error',
        { name: 'setInterval', message: 'Polling is not a substitute for the realtime architecture. Use the event bus / scheduler abstractions.' },
      ],
    },
  },
  {
    /**
     * NestJS resolves constructor dependencies from `emitDecoratorMetadata`,
     * which only records a class when it was imported as a *value*. A
     * type-only import erases to `Function` and the container cannot resolve
     * it, so this rule is off for the Nest applications by necessity, not by
     * preference. The domain packages below keep it on.
     */
    files: ['apps/api/**/*.ts', 'apps/worker/**/*.ts'],
    rules: {
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },
  {
    // Pure domain packages must never depend on frameworks or I/O.
    files: ['packages/financial-core/**/*.ts', 'packages/trading-core/**/*.ts', 'packages/risk-core/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: 'react', message: 'Domain packages must stay framework-independent.' },
            { name: 'next', message: 'Domain packages must stay framework-independent.' },
            { name: '@nestjs/common', message: 'Domain packages must stay framework-independent.' },
            { name: '@nestjs/core', message: 'Domain packages must stay framework-independent.' },
            { name: '@prisma/client', message: 'Domain packages must not depend on infrastructure.' },
            { name: 'ioredis', message: 'Domain packages must not depend on infrastructure.' },
          ],
          patterns: [
            { group: ['node:*', 'fs', 'http', 'https', 'net'], message: 'Domain packages must be pure and I/O free.' },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.spec.ts', '**/*.test.ts', 'scripts/**/*.ts', 'prisma/seed.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      'no-restricted-imports': 'off',
    },
  },
);
