import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { BEGIN, END, measure } from './measure-repository';

/**
 * The figures in `docs/COMPLETION_STATUS.md`, against the repository.
 *
 * That document opens by warning that it went stale once silently, and says it
 * "is now regenerated from measurement rather than patched". Nothing
 * regenerated it. It went stale again in exactly the way it warns about, and
 * every figure was roughly half of reality: 16 packages against 20, 52 Prisma
 * models against 70, 161 routes against 237, 78,000 lines against 151,000.
 *
 * A warning about staleness is not a defence against it. This is.
 *
 * **Only the structural counts are pinned, and that is deliberate.** Apps,
 * packages, models, migrations and routes change rarely and on purpose, so a
 * mismatch is drift somebody should fix. Test and line counts move on almost
 * every commit; asserting them would produce a test that fails for everyone and
 * is deleted within the week — which is how a repository ends up with no check
 * at all, having had a very strict one. Those are stamped with the commit and
 * date they were taken at instead, so a reader can see their age rather than
 * assume they are current.
 */
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const doc = readFileSync(resolve(ROOT, 'docs/COMPLETION_STATUS.md'), 'utf8');

const block = (): string => {
  const start = doc.indexOf(BEGIN);
  const end = doc.indexOf(END);
  return start === -1 || end === -1 ? '' : doc.slice(start, end + END.length);
};

/** Every bolded number in the generated block, in order. */
const numbers = (text: string): number[] =>
  [...text.matchAll(/\*\*([\d,]+)[^*]*\*\*/g)].map((match) => Number(match[1]!.replace(/,/g, '')));

describe('the measured baseline', () => {
  it('is there, and is the generated block rather than prose', () => {
    expect(block(), `${BEGIN} … ${END} not found in docs/COMPLETION_STATUS.md`).not.toBe('');
    expect(block(), 'the block does not say when it was counted').toMatch(
      /Counted at `[0-9a-f]{7,}|Counted at `unknown`/,
    );
    // A block with no figures in it would satisfy every comparison below.
    expect(numbers(block()).length, 'no figures parsed out of the block').toBeGreaterThanOrEqual(5);
  });

  it('matches the working tree on everything that changes rarely', () => {
    const figures = measure();
    const text = block();
    for (const [label, value] of [
      ['applications', figures.apps],
      ['workspace packages', figures.packages],
      ['Prisma models', figures.models],
      ['migrations', figures.migrations],
      ['API routes', figures.routes],
    ] as const) {
      expect(
        numbers(text),
        `${label} is ${String(value)} and the document does not say so — run \`pnpm measure --write\``,
      ).toContain(value);
    }
  });

  it('can be regenerated by the command it names', () => {
    // A document pointing at a script that does not exist is the same defect
    // one layer along.
    const pkg = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8')) as {
      scripts: Record<string, string>;
    };
    expect(doc).toMatch(/pnpm measure --write/);
    expect(pkg.scripts['measure'], 'the document names a script nothing defines').toMatch(
      /measure-repository/,
    );
  });

  /**
   * And the sentence the whole document turns on. "Four of sixteen planned
   * phases are done" is a judgement, not a measurement, and it sits two
   * paragraphs above a block of measured figures where it reads like one. It
   * has to carry its date, or a reader takes a claim from months ago as today's.
   */
  it('dates the claim it cannot measure', () => {
    /**
     * Whitespace-tolerant, because the first version of this was not and the
     * sentence wraps: `Four of sixteen planned\nphases are done`. It matched
     * nothing, returned early, and passed — a probe that could not fail,
     * sitting in a file written to stop exactly that.
     *
     * And a missing sentence is now a failure rather than a pass. If somebody
     * rewrites the claim, this test should be rewritten with it deliberately,
     * not satisfied by its absence.
     */
    const phases = /(\w+)\s+of\s+(\w+)\s+planned\s+phases\s+are\s+done/.exec(doc);
    expect(phases, 'the phase claim has moved — update this test with it').not.toBeNull();

    /**
     * The date has to be part of the claim, not merely nearby. A 400-character
     * window around it also catches the "3 September 2026" in this document's
     * own header, so a window would have passed on a sentence carrying no date
     * at all.
     */
    const sentence = doc.slice(phases!.index, doc.indexOf('.', phases!.index + 40) + 1);
    expect(sentence, 'the phase count reads as measurement and carries no date').toMatch(
      /as of [^.]*20\d\d/i,
    );
  });
});
